### Test Elasticsearch is running
GET http://localhost:9200/

### Confirm that the index exists
GET http://localhost:9200/wine


### details about the index
GET http://localhost:9200/wine/_settings?pretty

#### See mapping
GET http://localhost:9200/wine/_mapping?pretty

### show how many documents are loaded on Elasticsearch
GET http://localhost:9200/wine/_count?pretty

####
POST http://localhost:9200/wine/_search?pretty
content-type: application/json

{
  "suggest": {
    "result": {
      "text": "cabernay",
      "term": {
        "field": "all_text"
      }
    }
  }
}


###
GET http://localhost:8003/api/v1/catalog/es-wine-search-words/?query=cabernay
