name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare services
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          sleep 10s
          docker-compose exec -T server coverage run manage.py test
          docker-compose exec -T server coverage report
          docker-compose down

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

